#ifndef GAME_ENUMS_HPP
#define GAME_ENUMS_HPP

enum enemy_difficulty {
    ENEMY_DIFFICULTY_EASY,
    ENEMY_DIFFICULTY_NORMAL,
    ENEMY_DIFFICULTY_HARD
};

enum enemy_texture {
    ENEMY_REAR_TEXTURE,
    ENEMY_REAR_UP_TEXTURE,
    ENEMY_REAR_DOWN_TEXTURE,
    ENEMY_REAR_LEFT_TEXTURE,
    ENEMY_REAR_RIGHT_TEXTURE,
    ENEMY_FRONT_TEXTURE,
    ENEMY_FRONT_UP_TEXTURE,
    ENEMY_FRONT_DOWN_TEXTURE,
    ENEMY_FRONT_LEFT_TEXTURE,
    ENEMY_FRONT_RIGHT_TEXTURE
};

enum material {
    MATERIAL_PYRITE,
    MATERIAL_WOLFRAMITE,
    MATERIAL_CARNEOL,
    MATERIAL_MOLDAVITE,
    MATERIAL_RUBY,
    MATERIAL_SAPPHIRE
};

#endif
