#ifndef GAME_ENUMS_HPP
#define GAME_ENUMS_HPP

enum material {
    MATERIAL_PYRITE,
    MATERIAL_WOLFRAMITE,
    MATERIAL_CARNEOL,
    MATERIAL_MOLDAVITE,
    MATERIAL_RUBY,
    MATERIAL_SAPPHIRE
};

#endif
